### ISSUE TITLE
"version" field should require a specific structure

### ISSUE THREAD

**Issue by ekeilty17** [ga4gh/data-repository-service-schemas#122]
I think it might be advantageous to make the "version" field in the data object and data bundle have a required structure such as "x.x.x" for the following reasons.

Currently, the below are all equally valid ways the client could version their object (valid as in it compliant with the spec not that it should be done this way).
`"version" : "v1"`
`"version" : "1.0"`
`"version" : "This is the first version of this object"`

Why this is a problem:
1) I think it gives the client too much freedom when naming their version as shown by the third example. 
2) If the version can be any string, then I as the implementor cannot assume anything about the structure of that string. This means there is not a straight forward way for my application to figure out the order of the versions. This may be a corner case, but consider this scenario. Say someone has version 1 and version 2 of a data set and wants to input both of them into the dos server. They carelessly input version 2 first and version 1 second. If my application cannot distinguish version 1 from version 2, then it will assume version 1 is the latest version because it was the most recent object that was input into the server.

My proposed solution:
A common format for version is "x.x.x". So if we require versions to be of that format it would solve a few problems and avoid a lot of head aches for those implementing it.

**Comment by denis-yuen** [comment]
I would consider using semantic versioning https://semver.org/
There are some libraries that can be relied on to do version comparisons as in 2)

**Comment by david4096** [comment]
These schemas are meant to be unopinionated about how versions are represented, as long as they can be represented by strings. For the demonstration server, using semantic versioning wouldn't be a problem, but would not be suggestive of how others should implement.

It is expected that the latest version is returned, and that implementors will provide timestamps as necessary to reason within their versioning schemes.

DOS was developed to interoperate with two data stores, indexd and HCA DSS. indexd using checksums for versions, and DSS uses timestamps. 

Do you have an implementation that uses semantic data versioning, as opposed to timestamps? If so, we would like to demonstrate that we can interoperate with it, either by adding an application for indexing into https://github.com/ohsu-comp-bio/dos_connect or by creating a small interoperability layer.

**Comment by david4096** [comment]
@ekeilty17 I'd like to close this by better detailing the expected behavior based on the current underlying stores we support. I added a note in this issue about the various ways versions might be represented in practice, including semantic versioning. Sound ok?
