### ISSUE TITLE
Map of array of strings

### ISSUE THREAD

**Issue by kellrott** [ga4gh/data-repository-service-schemas#15]
The added `system_metadata` and `user_metadata` fields allow for tagging of strings to key values, but a more 'robust' model may be to have a map to a repeated string. Synapse.org uses that model for their object properties. 

So that 
https://github.com/ga4gh/data-object-schemas/blob/7858f2005944d8bb73e2e5c7f2447c3c459e625d/proto/data_objects.proto#L88

would be something like
` map<string, google.protobuf.ListValue> system_metadata = 12; `

**Comment by david4096** [comment]
@cmungall @kellrott both great points. A reason to go <string, List> is that we can, technically, capture all sorts of data types and it is "easier" to write client code against. In this spirit I had added an extensible [`Attributes` field to the genomics API schemas](https://github.com/ga4gh/ga4gh-schemas/blob/master/src/main/proto/ga4gh/common.proto#L191). This has the benefit of being able to add types of your own choosing from the data model (i.e. Ontology Terms).

For DOS, I hope to simply have full, simple, easily indexable, high fidelity representation of the original metadata. 

Forcing a <string, List> structure can be onerous and is another translation layer needed for any interopability with an underlying data source. It can be done of course, and you can see how to store arbitrary hierarchical data in that format in this [notebook on tagStorm](https://github.com/david4096/bioapi-examples/blob/tagstorm/python_notebooks/tagStorm.ipynb).

So, a `struct` as I am pushing for in this [pull request](https://github.com/ga4gh/data-object-schemas/pull/24/files#diff-df38bc2ef293a30fb0ef340ee52b6dc7R19), will hopefully support both cases. Both string tagged ordered lists and arbitrary JSON documents should be interchanged without needing to string serialize.

The goal is to create the minimum layer for the interchange of data. Having highly ordered metadata makes indexing and querying easier, and so would be considered an "upgrade", or a service offered by an alternative index, perhaps?

**Comment by cmungall** [comment]
I think a struct as in your PR makes sense. It seems many emerging conventions like bdbag and [bagit-ro](https://github.com/ResearchObject/bagit-ro) use JSON-LD. Is there any best practice for JSON-LD in protobuf? The `@context` object could simply be injected into the struct/JSON object, but it would be good to have some kind of conventions documented.

**Comment by david4096** [comment]
@cmungall I've reworked the schemas to remove protobuf. Can you provide instruction on how best to annotate another services metadata with the context properly? Do you have a standing service I could work with?

For example, [in this notebook](https://github.com/david4096/dos-gdc-lambda/blob/master/gdc-analyze-htseq.ipynb) I use the DOS client to explore GDC data. It seems like by defining the metadata schema for GDC and providing it for this specific instance, clients could better reason about responses. Is the best practice to modify the swagger for each installation? Is there a good way to decouple reasoning about JSON schemas and the static OpenAPI descriptions?

Excuse me for belaboring it, but by "injecting the `context`" you mean that when a service implements DOS, they would add to their instance an `@context` to the metadata JSON which points to a URI to describe its semantic meaning?

Thanks for taking the time to respond. I think any conventions along these lines would concretely improve the client experience, hopefully without adding complexity to the schema. I would like to take a stab at demonstrating this for the GDC metadata.

**Comment by cmungall** [comment]
I can think of a number of approaches. One would be for the OpenAPI to specify that the metadata object is an arbitrary JSON object, interpreted as JSON-LD, with additional recommendations about what vocabs to use. This has higher flexibility but additional complexity for clients.

Another would be to adopt a standard (e.g. DATS, HCLS, schema.org dataset descriptions) and enshrine this directly in the swagger description. This has less flexibility but easier for clients.

Or we could have a hybrid approach with a standard subset enshrined in the schema, and then an arbitrary JSON(LD) object for everything else

**Comment by david4096** [comment]
Without further discussion I'd like to close this with some documentation providing suggestions for metadata serialization. DOS does not intend to solve that problem. Allowing arbitrary JSON as metadata allows easy interop with underlying stores. We'll suggest providing a schema for understanding your metadata document if its available, but not require it.
