### ISSUE TITLE
Add contributing doc

### ISSUE THREAD

**Issue by david4096** [ga4gh/data-repository-service-schemas#156]
a la https://github.com/ga4gh/workflow-execution-service-schemas/pull/84/files

**Comment by natanlao** [comment]
Do you want an in-repo `CONTRIBUTING.md` or would adding some of the info you mentioned to this [ReadTheDocs page](https://data-object-service.readthedocs.io/en/latest/contributors.html) be sufficient?

**Comment by natanlao** [comment]
Repo changed to HubFlow, now being tracked in #206
