### ISSUE TITLE
updated documentation: expected behavior

### ISSUE THREAD

**Issue by bwalsh** [ga4gh/data-repository-service-schemas#17]
It would be useful to document expected behavior for:
* versioning
* alias
* metadata updates
* other

Kickoff discussion:

![image](https://user-images.githubusercontent.com/47808/31735984-6e183ad6-b411-11e7-9b73-86ab29af19dc.png)

**Comment by david4096** [comment]
@bwalsh Do you have more diagrams like these?

**Comment by david4096** [comment]
We should add details of different versioning schemes to follow up on https://github.com/ga4gh/data-object-service-schemas/issues/122 including semantic versioning.
