### ISSUE TITLE
Assist with region metadata

### ISSUE THREAD

**Issue by bwalsh** [ga4gh/data-repository-service-schemas#18]
https://github.com/ga4gh/data-object-schemas/blob/develop/proto/data_objects.proto#L78

We should validate that a URL is sufficient to determine:
* platform-provider
* endpoint
* region 
* other

This is needed by the workflow to determine optimal move-code-to-data and minimize-egress-charges

**Comment by david4096** [comment]
Can this be in the `system_metadata`? Should these be named parameters of a URL?

**Comment by david4096** [comment]
To close this, we should provide instruction in the documentation about how details about a key in S3 can be represented in the `system_metadata`.

dos_connect shows how these data can be gathered from the s3 API:

https://github.com/ohsu-comp-bio/dos_connect/blob/master/dos_connect/apps/inventory/s3_inventory.py#L17
