### ISSUE TITLE
DRS Schema Updates

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/data-repository-service-schemas#192]
Let's start with some simple changes to the schema to start our transition to DRS.  See #187 and #191

**Comment by briandoconnor** [comment]
see #193 PR... open for discussion mainly, not ready for a merge

**Comment by briandoconnor** [comment]
See #196 too.

**Comment by natanlao** [comment]
Hi @briandoconnor! Yes, I have time this sprint to review, though I am out of the office until early next week for finals.

**Comment by briandoconnor** [comment]
Thanks @natanlao !  Good luck on your finals!  In the mean time I will work on #194 and the PR that Deepak and I will eventually raise to go with that one.  For #194 I'm starting with the feature branch for issue-192 as a start.
