### ISSUE TITLE
Partial repository rename

### ISSUE THREAD

**Issue by natanlao** [ga4gh/data-repository-service-schemas#196]
The Data Object Service is being renamed to the Data Repository Service. The rename will not be fully implemented until product approval / 1.0, but the current repository rename will stay. To this end, we need to make several changes to maintain consistency:

- [x] Recreate the repository ga4gh/data-object-service-schemas so that we can set up a GitHub pages redirect between the old Swagger UI and the new one (or find a different, better way to accomplish this)
- [ ] Update Travis badge to point to new repository name
- [ ] Document name change timeline more clearly in ReadTheDocs, README
- [ ] Ensure Snyk tests are properly configured for name change

I don't believe this list is exhaustive at the moment

**Comment by natanlao** [comment]
@david4096 Can you help with the first task?

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

Email sent to Rishi about fixing the dead swagger link.

**Comment by natanlao** [comment]
Rescoping parts of this issue as #206, will close this with #192
