### ISSUE TITLE
Update master to get latest docs from develop

### ISSUE THREAD

**Issue by natanlao** [ga4gh/data-repository-service-schemas#206]
In the interest of time, #192 is being merged with changes that have not been propagated entirely through the codebase. In particular, we need to update the documentation to reflect new paths (i.e. `/ga4gh/dos/v1/` to `/ga4gh/drs/v1/`) and the newly-named Bundles and Objects, to ensure that Snyk testing is properly configured for this repository, and to properly document the name change.

**Comment by natanlao** [comment]
Also need to update repository configuration and documentation to be consistent with HubFlow.

**Comment by briandoconnor** [comment]
Sounds like we need to merge into master soon so all the changes are up to date

**Comment by jaeddy** [comment]
@briandoconnor — see comment I made on @natanlao's PR #211:

> For WES, we had agreed to make `develop` the main "source of truth" for docs, status badges, and GitHub Pages content. While `master` would be the default branch visible to new visitors (post 1.0), it mostly functions as a passthrough for releases.
> 
> I don't think this is worth addressing here, but making a note that we should try to sync up on branch usage, PR procedure, etc. across repos (whether it's following "HubFlow" or something else).

While merging to `master` on a more regular cadence could be the solution, we might also want to make some tweaks to the build system itself.

**Comment by briandoconnor** [comment]
I'm making a release branch for a v0.0.1 that shows the starting point for DRS from our DOS work. It's just the endpoints after the rename from DOS -> DRS. So we can easily use this moment in time release as we think about bringing in more endpoints/features into DRS on the road to v1.0.

https://github.com/ga4gh/data-repository-service-schemas/tree/release/0.0.1

I have a few small things to fix here but this way I can merge this into master and work on develop can continue without waiting for a develop to master merge. The release branch is the hubflow process.

**Comment by briandoconnor** [comment]
See https://github.com/ga4gh/data-repository-service-schemas/pull/237... I'm waiting to see if it passes the checks and will then push to master.  I'm a little afraid it might break some things but I'm trying to get 1) master up to date with develop as it was in the initial DOS->DRS transition and 2) get the pypi integration working.

**Comment by briandoconnor** [comment]
Closing this
