### ISSUE TITLE
Clean list of metadata fields

### ISSUE THREAD

**Issue by rishidev** [ga4gh/data-repository-service-schemas#216]
From the Cloud Jan 2019 Hackathon

**Comment by briandoconnor** [comment]
I think this is just getting concrete about which fields we support in the GET method

**Comment by briandoconnor** [comment]
@susheel do you want to lead this one?

**Comment by briandoconnor** [comment]
Susheel is OK with the current metadata fields.  He'll take one last look just to check and leave his thoughts.

**Comment by delagoya** [comment]
One comment on line 192: 

https://github.com/ga4gh/data-repository-service-schemas/blob/52dc74b984f39660ba5f35ba3408e625f6e498f4/openapi/data_repository_service.swagger.yaml#L192

This should really be ("ETag")[https://en.wikipedia.org/wiki/HTTP_ETag] as the underlying algorithm is not exposed to the user for reconstruction of the tag independent of S3. Also other other object store systems may calculate checksums for multi-part uploads and put that in the ETag header.

**Comment by dglazer** [comment]
PR #246 is now merged
