### ISSUE TITLE
Define syntax for describing access methods - Duplicate?

### ISSUE THREAD

**Issue by rishidev** [ga4gh/data-repository-service-schemas#217]
including region hints, protocols, URIs ...

from the hackathon doc:

Getting explicit about the “protocols” supported in the URLs returned e.g. Aaron mentioned there are 5 that cover maybe 95% of use cases 1) signed URLs, 2) google, 3) Amazon, 4) Azure native URL, and 5) OpenID token HTTPS. Can we get explicit about these in the spec?

**Comment by briandoconnor** [comment]
Can this be done as part of #213 ?

**Comment by sarpera** [comment]
@briandoconnor I would say yes.
