### ISSUE TITLE
Define a /service-info endpoint

### ISSUE THREAD

**Issue by rishidev** [ga4gh/data-repository-service-schemas#218]
GA4GH Schemas need a /service-info endpoint.

For reference this is being defined by Discovery Networks, [intended final home is here](https://github.com/ga4gh-discovery/service-info). See also the [Spreadsheet with an overview of GA4GH endpoints](https://docs.google.com/spreadsheets/d/1_h90aCZPrIVTkvqVIkxK8y0FHpxfa2k2SQk4gnG26LM/edit#gid=261344965).

**Comment by dglazer** [comment]
Closing, since we now have a /service-info endpoint. (We can create new issues if there are specific new types of info we want to return.)
