### ISSUE TITLE
Remove no-longer-needed methods and attributes

### ISSUE THREAD

**Issue by rishidev** [ga4gh/data-repository-service-schemas#219]
Maybe list endpoints?

**Comment by sarpera** [comment]
Relates to #221 #221

**Comment by sarpera** [comment]
Assuming DRS v1.0 is still thought to be a read-only API:

### Methods

**Keep**
- `GET /service-info`
TBD in #218 
- `GET /bundles/{bundle_id}` - Retrieve a Data Bundle
- `GET /objects/{object_id}` - Retrieve a Data Object

**Remove**
- `POST /bundles` - Create a new Data Bundle
- `DELETE /bundles/{bundle_id}` - Delete a Data Bundle
- `PUT /bundles/{bundle_id}` - Update a Data Bundle
- `GET /bundles/{bundle_id}/versions` - Retrieve all versions of a Data Bundle
- `POST /objects` - Make a new Data Object
- `DELETE /objects/{object_id}` - Delete a Data Object index entry
- `PUT /objects/{object_id}` - Update a Data Object`

**Not sure**
- `GET /bundles` - List the Data Bundles
Need to refine query params.
- `GET /objects` - List the Data Objects
- `GET /objects/{object_id}/versions` - Retrieve all versions of a Data Object

### Attributes
TBD

**Comment by susheel** [comment]
My £0.02p for `DRS v1.0` (will not be worth much after March 2019 ;)

**Keep**
- `GET /service-info` - DRS Service Information (See #218)
- `GET /bundles/{bundle_id}` - Retrieve a Data Bundle (See #221)
- `GET /objects/{object_id}` - Retrieve a Data Object

**Update**
- `GET /bundles` - List the Data Bundles (Clean up metadata and request params)
- `GET /objects` - List the Data Objects (Clean up metadata and request params)

**New**
- `GET /objects/{object_id}/access` - Retrieve a Data Object bytes (See #213)

**Comment by dglazer** [comment]
I started working on this in the `feature/issue-219-trim-methods` branch -- so far I'm just removing the clearly out-of-scope bits.

**Comment by briandoconnor** [comment]
@dglazer since you're going for absolute minimal here for 0.1 to get the consensus of the Drivers I think it makes sense to remove the list methods.  I know several of these methods will come back but I think you're going for the bare minimum for v0.1 and we can add things back in in subsequent 0.x releases.

**Comment by dglazer** [comment]
Fine with me -- do you want to approve the initial PR (#233) and then I'll do a fast-follow with another one before we close out this issue?

**Comment by dglazer** [comment]
Per offline discussion with @briandoconnor, I went ahead and removed the List methods also. (I expect we'll eventually reintroduce something equivalent, but maybe as part of our Search/Discovery integration, instead of as a standalone piece of DRS. In any case, they're not part of the minimal 0.1 surface.)

**Comment by briandoconnor** [comment]
I took a look at the generated docs:

https://ga4gh.github.io/data-repository-service-schemas/preview/feature/issue-219-trim-methods/docs/

and

https://ga4gh.github.io/data-repository-service-schemas/preview/feature/issue-219-trim-methods/swagger-ui/#/

and compared to the current version on Develop:

https://ga4gh.github.io/data-repository-service-schemas/preview/develop/swagger-ui/#/DataRepositoryService

Definitely minimal :-) but I think it will be help us to focus in on issues #213 and #229 in preparation for v0.1 before adding in more endpoints/features.  It's key we get a PR for these issues and get Drivers to agree on how we get a bundle/file and ultimately retrieve bytes.  Despite all the features of DOS this critical part of the spec was left open and we need DRS to focus on auth and finding/getting bytes.

I'm going to merge but, in the mean time, I'm making a release branch for a v0.0.1 that shows the starting point for DRS from our DOS work.  It's just the endpoints after the rename from DOS -> DRS.  So we can easily use this moment in time release as we think about bringing in more endpoints/features into DRS on the road to v1.0.

https://github.com/ga4gh/data-repository-service-schemas/tree/release/0.0.1

I have a few small things to fix here but this way I can merge this into master and work on develop can continue without waiting for a develop to master merge.  The release branch is the hubflow process.
