### ISSUE TITLE
Support for public/protected/private

### ISSUE THREAD

**Issue by rishidev** [ga4gh/data-repository-service-schemas#220]
This is related to what a user sees in the metadata responses I believe... Susheel was interested in this and might have more details.

**Comment by dglazer** [comment]
@susheel -- I think the auth discussion and changes that have happened since January cover this -- do you agree? If so let's close it; if not please add a comment describing what's left to address.

**Comment by dglazer** [comment]
@susheel -- now that the auth changes are all merged, is there anything left to do here? If not, please close.

**Comment by susheel** [comment]
Thanks @dglazer
