### ISSUE TITLE
Convert the intro sections from the spec doc into markdown

### ISSUE THREAD

**Issue by rishidev** [ga4gh/data-repository-service-schemas#222]

**Comment by dglazer** [comment]
FYI, the spec doc is at https://docs.google.com/document/d/1nVUrC5S06ahKjJtWOkb6Q22UCyguTpiiBaZV7KDur0E/edit

I've created a branch issues/222-doc-overview for working on this.

**Comment by dglazer** [comment]
These changes are now merged. There's more doc work to do, but it should happen after we resolve pending conversations on the API itself (new methods, auth, etc.),
