### ISSUE TITLE
update the DRS repo Contributing.md and ga4gh.cloud page with info about hub flow etc.

### ISSUE THREAD

**Issue by rishidev** [ga4gh/data-repository-service-schemas#223]

**Comment by briandoconnor** [comment]
I updated https://github.com/ga4gh/wiki/wiki

**Comment by rishidev** [comment]
[Wiki page changes](https://github.com/ga4gh/wiki/wiki/Home/_compare/a924c38abc224438a33153bc13eff1e392625d5b...b31738a7e56a4378f84d931146adad328d5f06e0) are good

**Comment by rishidev** [comment]
Update of Contributing.MD document is also discussed in [#225 DRS Voting Procedures](https://github.com/ga4gh/data-repository-service-schemas/issues/225)

**Comment by rishidev** [comment]
Contributing also needs updates to reflect users with access to the repo should create branches within the repo, others should fork to their own space

**Comment by briandoconnor** [comment]
This is done @rishidev , I added info about folks with direct repo access.

**Comment by dglazer** [comment]
@briandoconnor -- these changes LGTM; feel free to close.
