### ISSUE TITLE
Rename previous DOS release tags

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/data-repository-service-schemas#227]
Let's rename the previous release DOS tags so we can start with 0.1 for DRS

**Comment by natanlao** [comment]
I have the bandwidth to handle this next sprint. This change may affect anyone referencing tags locally on a local repository cloned before tags were changed (as git will not automatically change tags in the background). That said, I think the only people who this *might* apply to are myself and @rshreya.

**Comment by natanlao** [comment]
This is done. Old DOS tags have been prepended with the `dos-` prefix, and the Releases page has been updated to reflect this, with as much history preserved as possible. There is no PR for this, so I will close pending sign off from @briandoconnor

**Comment by briandoconnor** [comment]
done!
