### ISSUE TITLE
should we maintain an object "type" ?

### ISSUE THREAD

**Issue by bwalsh** [ga4gh/data-repository-service-schemas#23]
See indexd ... 
https://github.com/LabAdvComp/indexd/blob/master/indexd/index/schema.py#L13-L18

```
    "form": {
      "enum": [
        "object",
        "container",
        "multipart"
      ]
    }
```

**Comment by david4096** [comment]
Since we have the `bundle` concept we don't need container. Multipart can probably be a metadata tag, so perhaps not.
