### ISSUE TITLE
refine the list of AccessMethod type values

### ISSUE THREAD

**Issue by dglazer** [ga4gh/data-repository-service-schemas#240]
Following up on the initial `type` list for `AccessMethod`, as enumerated in #236:
- how do we want to support  htsget? My first thought is it should be a `type` = `htsget` of its own, where the `access_url` is required to support the htsget protocol, vs. just being a place to fetch bytes.
- do we want our initial `type` list to only include methods that we expect somebody to have implemented by v1 launch, or should we lean further into the hypothetical future? I'm inclined to trim it back to only things that will be live in 2019, once we know what that list is.
- can we combine `http` and `https` into one? I expect most servers will only use one of them, and as a client I don't think I would ever have interesting logic to pick one vs. the other -- if I intend to use HTTP, I'll pick that `type` and use whatever `access_url` I'm given.

**Comment by briandoconnor** [comment]
Suggestion: Let's take out the access methods that aren't in use by implementers.

**Comment by briandoconnor** [comment]
So here's the current list:

- s3
- gs
- ftp
- sftp
- http
- https
- nfs
- globus
- aspera
- gsiftp
- local

I *think* we need the following for 2019:

- s3
- gs
- https
- htsget
- local

But what do implementers need?

**Comment by briandoconnor** [comment]
See #249 , the PR for the changes proposed here.  Let's keep that PR feature branch in sync with what the drivers/implementers here need in 2019

**Comment by susheel** [comment]
@briandoconnor For ELIXIR we need:
- local [MUST]
- ftp [MUST]
- globus [MUST]
- gsiftp [MUST]
- http(s) [NICE]
- s3 [NICE]
- htsget [NICE]

**Comment by ohofmann** [comment]
Vote for s3 and htsget from the AGHA side (not an implementer though, mind you).

**Comment by mattions** [comment]
@briandoconnor from SBG we are looking at these for our use-cases:

- s3 [MUST]
- gs [MUST]
- https [NICE]
- htsget [MUST]
- local [NICE]

**Comment by ddietterich** [comment]
For Jade Data Repo:
- gs [MUST]
- s3 [MUST]

**Comment by briandoconnor** [comment]
Awesome!  Thanks so much folks for the quick reply.  I updated the feature branch.

**Comment by delagoya** [comment]
I would suggest using `file` instead of `local` since this is an official [URI scheme](https://tools.ietf.org/html/rfc8089)

**Comment by briandoconnor** [comment]
OK, @delagoya I made that change

**Comment by jorizci** [comment]
@briandoconnor For EGA we need:
- http(s)
- s3
- htsget

**Comment by briandoconnor** [comment]
Awesome folks, so it's looks like we're converging on the list:

   - s3
    - gs
    - ftp
    - gsiftp
    - globus
    - htsget
    - https
    - file (aka local)

**Comment by dglazer** [comment]
PR #249 is now merged.
