### ISSUE TITLE
Data Access Metadata

### ISSUE THREAD

**Issue by david4096** [ga4gh/data-repository-service-schemas#25]
How should we represent various data access levels? Some registries will expose the metadata for a file, but provide a link to that file that one cannot access without authorization. How do we guarantee that the right metadata are available to allow them to request access?

In the testing I've done against the GDC public API the `controlled` and `open` keys can be used.

Under the heading _Filter Public Data_
https://gist.github.com/david4096/30b17166d27d992f7bc4e1eea3b6a2af
```
x['urls'][0]['system_metadata']['access'] == 'open'
```

Can we implement a schema that supports the various access levels more clearly? We would like to avoid the situation where one has a registry message, a URL, a 403 response and no recourse. 

This issue is meant to capture conversation that we can distill into a useful schema that supports the repositories we hope to support.

**Comment by geoffjentry** [comment]
A little exposition would be nice

**Comment by david4096** [comment]
Updated @geoffjentry

**Comment by geoffjentry** [comment]
Thanks :)
