### ISSUE TITLE
Add crc32c to the set of allowed hashes

### ISSUE THREAD

**Issue by ddietterich** [ga4gh/data-repository-service-schemas#250]
crc32c is the content hash supported by Google Cloud Storage for all blobs. GCS only generates an md5 hash for non-composite objects. 

[Hashes and ETags: Best Practices](https://cloud.google.com/storage/docs/hashes-etags)

The (Broad/Verily) Jade data repository team would like to return crc32c as one of the hashes for blobs.

**Comment by susheel** [comment]
@ddietterich We can add it to the description. Would that help?

The Checksum type description lists the possible values, but are not explicitly defined as enums. So you are free to add any checksum type.

**Comment by ddietterich** [comment]
Ah, I mis-read it. No change needed than. Thanks!
