### ISSUE TITLE
Nit: Do we really want the "format: date-time" clause on dates?

### ISSUE THREAD

**Issue by ddietterich** [ga4gh/data-repository-service-schemas#255]
When using swagger-codegen into Java, the result of `format: date-time` is to have the datatype set to OffsetDateTime. That datatype does not generate an RFC3339 string date as output.

For our implementation, we are removing that clause and returning an RFC3339 string as the response.

**Comment by susheel** [comment]
This may be a specific issue related to the swagger-codegen for Java. The [OAS 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) defines the `date-time` to be [RFC3339](http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14) compliant.

**Comment by ddietterich** [comment]
I expect you are right, Susheel. The problem seems to be when the generated code converts the OffsetDateTime to string, it is written as the component integers - not in any date format. Anyway, easy enough for us to fix and generate the compliant string.

**Comment by jaeddy** [comment]
Agree that this seems to be a problem with the Java codegen library, as opposed to the spec itself. I'd prefer that the date-time categorization be specified in Swagger/OpenAPI, as it at least provides context for the implementer (that they can debug, if needed).

**Comment by susheel** [comment]
Closing this issue.
