### ISSUE TITLE
resolve URI convention

### ISSUE THREAD

**Issue by dglazer** [ga4gh/data-repository-service-schemas#259]
Splitting this off from #252  -- let's use this issue to discuss our desired URI convention, assuming that #258 (Bundle/Object unification) lands.

**Comment by dglazer** [comment]
From https://github.com/ga4gh/data-repository-service-schemas/issues/252#issuecomment-487376045:

Here's another possible, slightly simpler, approach to URI strings:

> For convenience, including when passing content references to a WES server, we define a recommended URI syntax for DRS-accessible content. Strings of the form `drs://<server>/<id>` mean “you can fetch the DRS content with id `<id>` from the DRS server at `<server>`".
> 
> For example, if a WES server was asked to process `drs://drs.example.org/314159`, it would know that it could issue a GET request to `http://drs.example.org/ga4gh/drs/v1/objects/314159` to learn how to fetch that object.

**Comment by jcapka** [comment]
There was talk of supporting a scheme like `drs://<id>` in the future. That is not a valid URI, however `drs:<id>` is, which would allow the use of slashes in the ID without being ambiguous.

**Comment by dglazer** [comment]
_From Cloud workstream meeting this morning in Hinxton:_
After talking through various options, we agreed on the approach listed above : `drs://<server>/<id>`

Full list of DRS URI schemes we discussed (all assuming that bundles and objects are unified):
1. **proposal: `drs://<server>/<id>`**
    * **promise is that the server at `<server>` speaks DRS and returns DRS JSON**
    * pro: simple
    * pro: easy for clients to know what to do
    * con: what if the server moves?
    * con: what if the id is available on multiple servers?
2. proposal: `drs://<id>`
    * pro: even simpler
    * pro: allows truly permanent, portable ids
    * con: requires a central broker, possibly multiple resolvers
    * con: won’t know which resolver to use
3. proposal: `drs://<server>/ga4gh/v1/<id>`
    * pro: explicit mapping to http, simple
    * con: brittle to a particular DRS server and protocol
4. proposal: `drs://<drs-namepace>/<namespace-specific-string>`
    * e.g. `drs://server/<server>/<id>`
    * e.g. `drs://dataguid/<dataguid>`
    * pro: multiple ways
    * con: multiple ways
    * con: not needed; could just do option 1 with `drs://dataguid.org/<dataguid>`

**Comment by dglazer** [comment]
@jcapka -- good future suggestion -- I'd add it to the (not yet existent) issue discussing whether we should allow slashes in DRS IDs.

**Comment by dglazer** [comment]
PR #261 updates the documentation to resolve this issue.

**Comment by dglazer** [comment]
resolved by #261
