### ISSUE TITLE
Review product approval documentation

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/data-repository-service-schemas#265]

**Comment by rishidev** [comment]
[DRS document is here](https://docs.google.com/document/d/12eWLO4AUy0mojwGHPnN_dTLfYM4J9y_iav6hH21qHVY/edit?usp=sharing)

**Comment by rishidev** [comment]
[DRS Main Approval Document](https://docs.google.com/document/d/12eWLO4AUy0mojwGHPnN_dTLfYM4J9y_iav6hH21qHVY/edit?usp=sharing) - 

[REWS ](https://docs.google.com/document/d/1PF5mJWu7SUxxfy_vPn63fpxBqYimCIlNvr8ycU58bNo/edit?usp=sharing)/ 
[Security ](https://docs.google.com/document/d/1MaV8GX0xLLq3jZ8BGHGLEkY5rlHwWopyHOWEkV5NeiE/edit)/ 
[Partner Engagement](https://docs.google.com/document/d/1QzD8mt_PwETZXLjyh65_R1naISqhLJ1uYEnTCQEZoP0/edit)
