### ISSUE TITLE
Checksum compute for a bundle should only include its top-level contained blobs

### ISSUE THREAD

**Issue by junjun-zhang** [ga4gh/data-repository-service-schemas#279]
Should the text below be changed from `its top-level contained objects` to `its top-level contained blobs`?

https://github.com/ga4gh/data-repository-service-schemas/blob/9e2190d848db128fbf948d7e3eeb66168417f397/openapi/data_repository_service.swagger.yaml#L207-L210

The reason is simple, when a blob in a deeper level bundle changes, only its direct containing bundle needs to recompute the checksum, no need to propagate to higher level bundles.

This should work for bundles do not contain any blobs (only have sub-bundles),  it would be a checksum on empty string.

**Comment by dglazer** [comment]
I believe we need a unique checksum, even if it's expensive to compute, that reflects any change in the bundle, including in nested sub-levels.

**Comment by junjun-zhang** [comment]
Thanks @dglazer for clarification. I guess it would be a **best practice** to avoid creating very large bundles, certainly not with millions of  sub-bundles.
