### ISSUE TITLE
generated java swagger client missing model for GET '/objects/{object_id}' response

### ISSUE THREAD

**Issue by pr80ik** [ga4gh/data-repository-service-schemas#298]
When generating java client from the swagger spec as follows, the generated code is missing a response model for the API `GET '/objects/{object_id}'`. The model is generated, but not used in the API method signature.

Expected: The generated java client should have the correct response model.

generated java client as follows:
```sh
JAVA_BASE_PACKAGE="mydrsclient"
ARTIFACT_ID="drsclient"

JAVA_DRS_BASE_PACKAGE="${JAVA_BASE_PACKAGE}.${ARTIFACT_ID}"
JAVA_DRS_API_PACKAGE="${JAVA_DRS_BASE_PACKAGE}.api"
JAVA_DRS_MODEL_PACKAGE="${JAVA_DRS_BASE_PACKAGE}.model"
JAVA_DRS_INVOKER_PACKAGE="${JAVA_DRS_BASE_PACKAGE}.invoker"

JAVA_PACKAGE_VERSION="0.0.1-SNAPSHOT"

OUT_DIR="drs-swagger-codegen-api-client"

java -jar "${SWAGGER_CLI_JAR}" \
 generate \
 -i "${SWAGGER_DOC}" \
 --api-package "${JAVA_DRS_API_PACKAGE}" \
 --model-package "${JAVA_DRS_MODEL_PACKAGE}" \
 --invoker-package "${JAVA_DRS_INVOKER_PACKAGE}" \
 --group-id "${JAVA_BASE_PACKAGE}" \
 --artifact-id "${ARTIFACT_ID}" \
 --artifact-version "${JAVA_PACKAGE_VERSION}" \
 -l java \
 --library resttemplate \
 -o "${OUT_DIR}"
```

This is maybe because 'Object' is a build-in base class for all classes in java. And can be referenced without importing it explicitly. And the generated code is accidentally referencing the `java.lang.Object` instead of `mydrsclient.model.Object`.

This is likely a bug in the _swagger gen_, because you can refer to a custom `Object` class by always using the fully qualified name. However it leads to ugly code and is error prone. Also using the name `Object` for classes is discouraged.

If I change the swagger spec as follows, the generated client works as expected

```patch
--- drs-upstream.yaml	2019-08-24 06:48:32.000000000 -0700
+++ drs.yaml	2019-08-24 06:50:56.000000000 -0700
@@ -31,7 +31,7 @@
         '200':
           description: The `Object` was found successfully.
           schema:
-            $ref: '#/definitions/Object'
+            $ref: '#/definitions/DrsObject'
         '202':
           description: >
             The operation is delayed and will continue asynchronously.
@@ -187,7 +187,7 @@
           standard `type` value such as `md5`, `etag`, `crc32c`, `trunc512`, or `sha1`.
         example:
           sha-256
-  Object:
+  DrsObject:
     type: object
     required: ['id', 'self_uri', 'size', 'created_time', 'checksums']
     properties:
```

**Comment by dglazer** [comment]
Nice catch @pr80ik , and seems like an easy fix, since IIUC changing `Object` to `DrsObject` doesn't require changes to any existing code. I'll push through a fix tonight/tomorrow. (Unless you'd rather do it yourself.)
