### ISSUE TITLE
proposed change to ListDataObjectsRequest  (s/alias/aliases)

### ISSUE THREAD

**Issue by bwalsh** [ga4gh/data-repository-service-schemas#33]
current
```
    object_list_request = ListDataObjectsRequest(alias="OBJ1")
```
proposed
```
    object_list_request = ListDataObjectsRequest(aliases=["OBJ1"])
```
This would align it more with the underlying model, as it doesn't have a property of alias, rather [aliases](https://github.com/ga4gh/data-object-schemas/blob/master/proto/data_objects.proto#L93)

**Comment by david4096** [comment]
To clarify the query semantics, would you expect ALL Data Objects matching ANY of the provided aliases to be returned? Or ONLY DataObjects matching ALL of the provided aliases?

Note, this is a feature that isn't well supported on DSS on indexd afaik.
