### ISSUE TITLE
Support POST'ing of Passports to DRS endpoints

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/data-repository-service-schemas#348]
**DEADLINE**: please comment on the PR #363 before the next Cloud call on Sept 13th.  We will merge this PR then if there are no blocker comments.

In the TOPMed (BioData Catalyst) driver project (and applicable to GDC and NCI Drivers) we have been exploring different ways of interacting between Passport systems ([NIH RAS](https://auth.nih.gov/docs/RAS/serviceofferings.html) in this case) and a DRS server.  There are multiple proposals for how a Passport with Embedded Visas should be handed to a DRS server and BDCat has documented 3 different approaches we're considering [here](https://docs.google.com/document/d/1T3uYGS2yZflDbLRbG4uxhi8ICqk9C9xWPmJ0DQpFvDU/edit#heading=h.5atd0vqkj5vq).  We've largely settled on an approach where RAS Passports will be POST'd directly to a DRS server, see [here](https://docs.google.com/document/d/1amOGLwAbKkMSU6up_dHGhsuUF9SVFlllO0qjQSJYuVI/edit#heading=h.4uzh9l6x5chi).

In the RAS passport to DRS server flow (option 2, scenario 1) we would need a way to POST a RAS Passport to a DRS server and right now the /objects/{object_id}/access/{access_id} only supports GET.

This issue is accompanied by a feature branch [feature/issue-348-post-passport-v2](https://github.com/ga4gh/data-repository-service-schemas/tree/feature/issue-348-post-passport-v2) where I'm trying to update the schema to accommodate posts.

You can follow builds on [Travis](https://app.travis-ci.com/github/ga4gh/data-repository-service-schemas/builds)

Built docs can be found at [preview/feature/issue-348-post-passport-v2/docs](https://ga4gh.github.io/data-repository-service-schemas/preview/feature/issue-348-post-passport-v2/docs)

Swagger schema can be downloaded from the top of the docs above and visualized at https://editor.swagger.io

The PR: https://github.com/ga4gh/data-repository-service-schemas/pull/363

**Comment by ianfore** [comment]
Would this just be for Passport? Or are we offering POST for the other auth mechanisms that currently exist e.g. the payloads that are currently passed via Bearer tokens?

**Comment by briandoconnor** [comment]
PR was merged so closing
