### ISSUE TITLE
wrong response for PostObject?

### ISSUE THREAD

**Issue by dvoet** [ga4gh/data-repository-service-schemas#375]
https://github.com/ga4gh/data-repository-service-schemas/blob/eb3df1abecf182ac7bea61bac11f1951adb6f8ea/openapi/paths/objects%40%7Bobject_id%7D.yaml#L39

should this line refer to `200OkDrsObject` instead of `200OkAccess`

**Comment by jb-adams** [comment]
Hi @dvoet I think you are correct.

@briandoconnor can you confirm? Should the `POST /objects/{object_id}` should return an object of type `DrsObject`, or `AccessMethod`? If the former, we should update this line.

@dvoet, do you want to submit a pull request?

**Comment by briandoconnor** [comment]
Yep, not sure how this typo got in there but @dvoet is totally right here.  

Doug, in your PR you want to merge to "master".  Can you change to "develop" instead?  I'm happy to then to the release process to get out a 1.2.1 that includes this fix.

Thanks!!!

**Comment by briandoconnor** [comment]
merged and closing
