### ISSUE TITLE
Where can I find executable apps/scripts and documents for registering the new objects?

### ISSUE THREAD

**Issue by polarbear127** [ga4gh/data-repository-service-schemas#383]
Dear developers,

I've played the starter kit for a while, but I'd like to modify some parts to implement DRS and WES in my institute properly.  

There is only a jar file in the starter kit. Besides, I can only find documents using GET/POST APIs to retrieve DRS objects. There is no document for submitting objects to register to the DRS. I can only use the UI admin API to do so. Where can I read the detailed API documents?

This repo looks like generates API documents only, correct? Where can I find resources to build up my own DRS/WES?

Sorry I might ask some noob questions.

Cheers,

**Comment by jb-adams** [comment]
hi @polarbear127 , thanks for your interest in DRS and the Starter Kit. Would you be able to submit these issues to the [DRS](https://github.com/ga4gh/ga4gh-starter-kit-drs) and [WES](https://github.com/ga4gh/ga4gh-starter-kit-wes) starter kit repos? This repo is only for the DRS specification.

We have an object registration API in the starter kit, but it's not very well documented as you've noticed. We are planning to add a Swagger UI.
