### ISSUE TITLE
Eventing and Subscriptions

### ISSUE THREAD

**Issue by david4096** [ga4gh/data-repository-service-schemas#6]
This issue is meant to capture the features necessary to support web hooks or eventing for objects or bundles.

**Comment by kellrott** [comment]
I would second this.
Many groups has opposed adding specific methods for search into the system, because there are a number of different platforms that would want to build on this. But if the system provide methods of subscribing or viewing the message queue, then systems would be able to scrape file and meta-data alterations.

We could start looking at some other systems to provide similar API requests.
Kafka-Rest:
https://github.com/confluentinc/kafka-rest

GitHub Webhooks:
https://developer.github.com/webhooks/

**Comment by bwalsh** [comment]
Agreed.  This will need to include the different platforms [s3,google,azure,ceph,swift]

**Comment by david4096** [comment]
@bwalsh could you expand?

**Comment by bwalsh** [comment]
https://github.com/ohsu-comp-bio/kafka-connect

![image](https://user-images.githubusercontent.com/47808/32525145-dad0e0d0-c3d7-11e7-8d07-326d120cc638.png)


* observation: long lived services to observe the object store and populate registry with data-object-schema records. These observations catch add, moves and deletes to the object store.

* inventory: on demand commands to capture a snapshot of the object store. Inventory commands populate the registry

**Comment by geoffjentry** [comment]
So now an implementation would need to be built on top of Kafka? or am i misunderstanding?

**Comment by david4096** [comment]
We would not require something like that and when it comes to "Eventing and Subscriptions", the challenge is certainly the implementation and not the schema.

Schema-wise one would like to be able to say, "for this ID, tell me if there is a modification by posting to this endpoint". This would allow one to create "alerts" pertaining to specific requests. Practically speaking, guaranteeing only-once delivery is technically complex.

This issue is meant to capture what features would be needed to support this and whether it is tractable. It is difficult for me to imagine *requiring* web hooks features for an instance of this service. Currently, the HCA is exploring subscriptions as a way to provide other access patterns.

**Comment by bwalsh** [comment]
I'll correct the diagram and remove the reference to Kafka.   It is not a
requirement.

As a practical matter those object stores need to be observed or
inventoried.  All of the object store implementations provide an eventing
model, the referenced project simply listens for those events from the
object store and translates them to a DOS object.  What the Observer does
with those DOS objects is implementation dependent.

There is some value to supporting existing workflows and capturing those
object records by observing the buckets they interact with.

I hear you regarding  ws-*.

**Comment by bwalsh** [comment]
I've restated the diagram to make it somewhat clearer.

* The implementation must to handle the CREATE,DELETE,MODIFY presented by the object stores and maintain the DOS registry.

* The client must be able to consume from the registry and maintain it's store



![image](https://user-images.githubusercontent.com/47808/32568479-36e62d30-c473-11e7-9927-7b3b3cdcb20c.png)
