### ISSUE TITLE
How to resolve services

### ISSUE THREAD

**Issue by tetron** [ga4gh/data-repository-service-schemas#74]
From Toronto F2F meeting:

How does DOS return services, such as htsget endpoints?  Is this a separate type from "DataObject" or should "DataObject" have a type field?

**Comment by tetron** [comment]
From Toronto F2F:

Ways to express this include `mime_type` on the DataObject, or fields in `system_metadata` or `user_metadata` on individual URLs.

**Comment by david4096** [comment]
If htsget has a mime_type, this seems like a natural way of encoding htsget endpoints. Other suggestions? @tetron ?

Is there some information providers would prefer to place in `/service-info` endpoint? https://github.com/ga4gh/data-object-service-schemas/issues/115

**Comment by david4096** [comment]
Although interoperability is demonstrated in https://github.com/ga4gh/data-object-service-schemas/pull/75 , to close this issue a service presenting htsget resources via DOS should be available, perhaps through an indexing script to https://github.com/ohsu-comp-bio/dos_connect ?
