### ISSUE TITLE
Provide use case(s) for data bundles

### ISSUE THREAD

**Issue by jaeddy** [ga4gh/data-repository-service-schemas#77]
Data bundles are currently a prominent part of the spec, in addition to data objects. I have a rough understanding of how various data coordinating / storage systems might use bundles to manage ingestion and movement of related files. However, I haven't seen any clear examples of what the corresponding interaction/process would look like with this API.

**Comment by geoffjentry** [comment]
And more important, which driver project needs them

**Comment by david4096** [comment]
This is a feed forward from HCA. Basically, they bundle orient their data to keep a sample or workflows inputs and outputs together logically. The bundle can be any logical list of objects. A targeted interop use case is to demonstrate the DOS Data Bundles easily serialize as bdbags format.

It goes something like, run a workflow, get some outputs of various file types, create a Bundle to logically relate them, then make that bundle discoverable by some workflow provenance. Although you could tag each data object in a way to allow the same feature, data bundles provide a way to group them in a canonical fashion. You can imagine having a bundle for all of the outputs of a workflow run tagged with a useful alias. Or the inputs to a workflow described as a single bundle.

http://bd2k.ini.usc.edu/tools/bdbag/

https://github.com/fair-research/concierge
