### ISSUE TITLE
Enumerating checksum types

### ISSUE THREAD

**Issue by david4096** [ga4gh/data-repository-service-schemas#89]
Checksum type is currently an open string. Would it be more usable as an enumerated set of values?

**Comment by david4096** [comment]
We can close this issue by reviewing the current documentation and creating a test showing checksums of each type support by HCA DSS (from dos-dss-lambda) and indexd (dataguids.org) can be represented in the spec.

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

Let’s consider using an enum to avoid collisions or duplications of hash algorithm names.
