### ISSUE TITLE
Endpoint info

### ISSUE THREAD

**Issue by david4096** [ga4gh/data-repository-service-schemas#92]
The ga4gh reference sequence retrieval API includes metadata about each endpoint in `info`. Similarly, the WES `/service-info` endpoint returns details of the running service.

To close this, add schema for a service info endpoint that can give metadata about the maintainer, number of available data objects, etc.

**Comment by lairdm** [comment]
I'm thinking in reference sequence retrieval we could switch to /service-info to at least keep the name consistent. This topic briefly came up in the Discovery Networks call yesterday, we were discussing hand-off briefly and if such an endpoint standardized across WSs could help with such things. I see the WES endpoint already has auth_instructions_url.

Last night I was mulling we if could get an agreement for a skeleton definition along the lines of

{
  <reserved>,
  "service": {
    "name": "service name",
    <service defined payload>
  }
} 

Where hand-off and other information useful across services would go in the reserved section. And service specific information would go under service, this would allow APIs like reference sequence retrieval to move forward with defining our service specific needs while maintaining backwards compatibility as the reserved section is defined over time (I don't think any WS has the time to take this on at the moment).

**Comment by rishidev** [comment]
Good suggestion lairdm - what we can do when consensus is reached here is point people to the result.
